---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("readxl")
library(readxl)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("writexl")
library(writexl)

#install.packages("openxlsx")
library(openxlsx)

# Load the clipr package
library(clipr)
```

```{r}

#main dataset 
industryjulyData <- read_excel("rtisajul2025.xlsx", sheet = "23. Employees (Industry)", skip = 6) #seasonally adjusted

#some other datsets I played around with
julyData <- read_excel("rtinsajul2025.xlsx", sheet = "32. Employees (NUTS1Age)", skip = 5) #not seasonally adjust 
SAjulyData <- read_excel("rtisajul2025.xlsx", sheet = "32. Employees (NUTS1Age)", skip = 5) #seasonally adjusted

```

#By industry 

```{r}
industry <- industryjulyData %>%
  select(Date, "Manufacturing", "Construction", "Wholesale and retail; repair of motor vehicles", "Transportation and storage", "Accommodation and food service activities", "Information and communication", "Finance and insurance", "Professional, scientific and technical", "Administrative and support services", "Public administration and defence; social security", "Education", "Health and social work") %>% 
  filter(Date %in% c("June 2025", "June 2024")) %>%
  rename("Wholesale and retail" = "Wholesale and retail; repair of motor vehicles", "Public administration and defence" = "Public administration and defence; social security",) %>%
  pivot_longer(
    cols = -1,  
    names_to = "industry",
    values_to = "value"
  ) %>% # 
  group_by(`Date`, `industry`) %>%
  summarise(total = sum(value, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = `Date`,
    values_from = `total`
  ) %>% #Used pivot_longer and pivot_wider as a way to transpose the dataset into format suitable for Flourish
  mutate(percIncrease = ((`June 2025` - `June 2024`)/`June 2024`)*100) %>%
  arrange(desc(percIncrease)) %>%
  write_clip()
```


#some other stuff I played around with 

#not seasonally adjusted
```{r}
agePayroll <- julyData %>% 
  pivot_longer(
    cols = starts_with(c("North", "South", "London", "West", "East", "Yorkshire", "Wales", "Scotland")),
    names_to = "region and age",
    values_to = "value"
  ) %>%
  separate("region and age", into = c("region", "age group"), sep = ": ") %>% # splits at first digit
  filter(Date %in% c("June 2025", "June 2024")) %>%
  group_by(`Date`, `age group`) %>%
  summarise(total = sum(value, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = `Date`,
    values_from = `total`
  ) %>% 
  mutate(percIncrease = ((`June 2025` - `June 2024`)/`June 2024`)*100) %>%
  write_clip()
```

#seasonally adjusted

```{r}
regionalDifferences <- SAjulyData %>%
  pivot_longer(
    cols = starts_with(c("North", "South", "London", "West", "East", "Yorkshire", "Wales", "Scotland")),
    names_to = "region and age",
    values_to = "value"
  ) %>%
  separate("region and age", into = c("region", "age group"), sep = ": ") %>%
  filter(Date %in% c("June 2025", "June 2024")) %>%
  filter(`age group` == "18-24") %>%
  group_by(`Date`, `region`) %>%
  summarise(total = sum(value, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = `Date`,
    values_from = `total`
  ) %>% 
  mutate(percIncrease = ((`June 2025` - `June 2024`)/`June 2024`)*100) %>%
  arrange(percIncrease) %>%
  write_clip()
```








