---
title: "R Notebook"
output: html_notebook
---
```{r}
#install.packages("readxl")
library(readxl)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("writexl")
library(writexl)

#install.packages("openxlsx")
library(openxlsx)

# Load the clipr package
library(clipr)
```

```{r}
julyData <- read_excel("rtinsajul2025.xlsx", sheet = "32. Employees (NUTS1Age)", skip = 5)
```


```{r}
agePayroll <- julyData %>% 
  pivot_longer(
    cols = starts_with(c("North", "South", "London", "West", "East", "Yorkshire", "Wales", "Scotland")),
    names_to = "region and age",
    values_to = "value"
  ) %>%
  separate("region and age", into = c("region", "age group"), sep = ": ") %>% # splits at first digit
  filter(Date %in% c("June 2025", "June 2024")) %>%
  group_by(`Date`, `age group`) %>%
  summarise(total = sum(value, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = `Date`,
    values_from = `total`
  ) %>% 
  mutate(percIncrease = ((`June 2025` - `June 2024`)/`June 2024`)*100) %>%
  write_clip()
  
  
```

